import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const PPFormulaFont = localFont({
  src: [
    { weight: "bold", path: "./../fonts/PPFormula-ExtendedBold.woff2" },
    { weight: "normal", path: "./../fonts/PPFormula-SemiCondensedMedium.otf" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="cs">
      <body className={PPFormulaFont.className}>{children}</body>
    </html>
  );
}
